const actions = {
  CREATE_PROJECT: "CREATE_PROJECT",
  CREATE_PROJECT_ERROR: "CREATE_PROJECT_ERROR",
  LOGIN_SUCCES: "LOGIN_SUCCES",
  LOGIN_ERROR: "LOGIN_ERROR",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_ERROR: "SIGNUP_ERROR"
};

export default actions;
